const { app, BrowserWindow } = require('electron');
const { mkdtempSync, writeFileSync } = require('node:fs');
const { tmpdir } = require('node:os');
const { resolve, join } = require('node:path');
const assert = require('node:assert/strict');
const { MATERIAL_PROOFS } = require('../dist-electron/shared/material-checks.js');
app.setAppPath(resolve(__dirname, '..'));
app.setPath('userData', mkdtempSync(join(tmpdir(), 'freddy-smoke-')));
app.commandLine.appendSwitch('use-fake-device-for-media-stream');
app.commandLine.appendSwitch('use-fake-ui-for-media-stream');
app.commandLine.appendSwitch('disable-background-timer-throttling');
if (!process.argv.includes('--visual')) BrowserWindow.prototype.show = function () {};
require('../dist-electron/desktop/main.js');
const pause = ms => new Promise(resolve => setTimeout(resolve, ms));
function validProof(requirement) {
  const checked = requirement.items;
  if (requirement.method === 'checklist') return { method: 'checklist', checked };
  if (requirement.method === 'text') return { method: 'text', checked, text: 'Resoluções registradas nas páginas 42 a 45.' };
  if (requirement.method === 'link') return { method: 'link', checked, url: 'https://example.com/backlog' };
  return { method: 'file', checked, fileName: `entrega${requirement.accept.split(',')[0]}`, fileSize: 1024 };
}
async function until(check, timeout = 20000) {
  const deadline = Date.now() + timeout;
  while (Date.now() < deadline) { const result = await check(); if (result) return result; await pause(100); }
  throw new Error('Tempo esgotado: ' + check.toString());
}
app.whenReady().then(async () => {
  try {
    const main = await until(() => BrowserWindow.getAllWindows().find(w => w.webContents.getURL().endsWith('/index.html')));
    assert.equal(main.getTitle(), 'FreddyBuddy');
    const evaluate = expression => main.webContents.executeJavaScript(expression, true).catch(error => { throw new Error(expression, { cause: error }); });
    await until(() => evaluate('Boolean(document.querySelector(".os-desktop"))'));
    assert.equal((await evaluate('window.baiStudyMain.getSession()')).phase, 'waiting');
    assert.equal(await evaluate('Boolean(document.querySelector(".os-icons button span")?.textContent === "Foco Total")'), false);
    assert.equal((await evaluate('window.baiStudyInstagram.getReels()')).length, 2);
    assert.equal(await evaluate('window.baiStudyInstagram.startStudying().then(() => false, () => true)'), true);
    await evaluate('document.querySelector(".os-icons button").click()');
    await until(() => evaluate('Boolean(document.querySelector(".instagram-home img")?.naturalWidth)'));
    assert.equal(await evaluate('document.querySelector(".instagram-nav button:nth-child(2)").getAttribute("aria-label")'), 'Reels');
    assert.equal(await evaluate('(() => { const image=document.querySelector(".instagram-home img").getBoundingClientRect(); const home=document.querySelector(".instagram-home").getBoundingClientRect(); return Math.round(image.width)===Math.round(home.width)&&Math.round(image.height)===Math.round(home.height); })()'), true);
    await evaluate('document.querySelector("button[aria-label=Reels]").click()');
    await until(() => evaluate('document.querySelectorAll(".reel").length === 2'));
    assert.equal(await evaluate('getComputedStyle(document.querySelector(".reels-feed")).scrollBehavior'), 'auto');
    assert.equal(await evaluate('getComputedStyle(document.querySelector(".reel")).scrollSnapStop'), 'normal');
    assert.equal(await evaluate('document.querySelectorAll(".reel video[src]").length'), 2);
    await pause(100);
    const reelMotion = await evaluate('new Promise(resolve => { const feed=document.querySelector(".reels-feed"); feed.dispatchEvent(new WheelEvent("wheel",{deltaY:120,bubbles:true,cancelable:true})); setTimeout(() => resolve({top:feed.scrollTop,height:feed.clientHeight,animating:feed.classList.contains("reels-feed--animating")}),150); })');
    assert.equal(reelMotion.animating, true);
    assert.ok(reelMotion.top > 0 && reelMotion.top < reelMotion.height, JSON.stringify(reelMotion));
    await until(() => evaluate('(() => { const feed=document.querySelector(".reels-feed"); return Math.abs(feed.scrollTop-feed.clientHeight)<2; })()'));
    await evaluate('document.querySelector("button[aria-label=Home]").click()');
    await pause(300);
    writeFileSync(join(app.getPath('userData'), 'instagram-home.png'), (await main.webContents.capturePage()).toPNG());
    await evaluate('document.querySelector(".os-chrome-icon").parentElement.click()');
    await evaluate('(() => { const input=document.querySelector(".os-google input"); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"aluno@gmail.com"); input.dispatchEvent(new Event("input",{bubbles:true})); })()');
    await pause(100);
    await evaluate('document.querySelector(".os-google").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))');
    assert.equal(await evaluate('Boolean(document.querySelector(".os-google"))'), true);
    await evaluate('(() => { const input=document.querySelector(".os-google input"); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"aluno@usp.br"); input.dispatchEvent(new Event("input",{bubbles:true})); })()');
    await pause(100);
    await evaluate('document.querySelector(".os-google").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))');
    await pause(100);
    await evaluate('(() => { const inputs=document.querySelectorAll(".os-usp input"); for(let i=0;i<inputs.length;i++){ Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(inputs[i],i===0?"12345678":"demo"); inputs[i].dispatchEvent(new Event("input",{bubbles:true})); } })()');
    await pause(100);
    await evaluate('document.querySelector(".os-usp form").dispatchEvent(new Event("submit", { bubbles: true, cancelable: true }))');
    await until(() => evaluate('Boolean(document.querySelector(".os-success"))'));
    await evaluate('document.querySelector(".os-browser > header > button").click()');
    await until(() => evaluate('window.baiStudyMain.getSession().then(s => s.phase === "active")'));
    await until(() => evaluate('Boolean(document.querySelector(".desktop-freddy"))'));
    assert.equal(await evaluate('document.body.textContent.includes("SEMANA DE PROVA DETECTADA")'), false);
    assert.equal(await evaluate('document.body.textContent.includes("FREDDY AO VIVO")'), false);
    assert.equal(await evaluate('document.querySelector(".brand b").textContent'), 'Foco Total');
    assert.equal(await evaluate('document.querySelector(".brand svg") !== null'), true);
    assert.equal(await evaluate('document.querySelector(".bonus-coins").title.includes("versão de desenvolvedor")'), true);
    assert.equal(await evaluate('window.baiStudyMain.dismissBuddy().then(() => false, () => true)'), true);
    const missions = await evaluate('window.baiStudyMain.getAcademy().then(s => s.missions)');
    assert.equal(await evaluate('document.body.textContent.includes("Freddy, repete isso")'), false);
    assert.equal(await evaluate('window.baiStudyMain.updateAcademy({type:"mission.complete",id:"jupiter-calculo"}).then(()=>false,()=>true)'), true);
    await evaluate('window.baiStudyMain.materialOpened("jupiter-calculo")');
    assert.match(await evaluate('window.baiStudyMain.getFredState().then(s=>s.message)'), /derivadas/);
    await evaluate('window.baiStudyMain.skinSelected("freddy_rock")');
    assert.match(await evaluate('window.baiStudyMain.getFredState().then(s=>s.message)'), /rock/);
    await evaluate('document.querySelectorAll(".mission-start")[1].click()');
    await until(() => evaluate('Boolean(document.querySelector(".material-verification input"))'));
    await pause(300);
    writeFileSync(join(app.getPath('userData'), 'material-check.png'), (await main.webContents.capturePage()).toPNG());
    await evaluate('(() => { document.querySelectorAll(".proof-check input").forEach(input=>input.click()); const input=document.querySelector(".proof-text input"); Object.getOwnPropertyDescriptor(HTMLInputElement.prototype,"value").set.call(input,"Resoluções nas páginas 42 a 45 do caderno"); input.dispatchEvent(new Event("input",{bubbles:true})); })()');
    await pause(100);
    await evaluate('document.querySelector(".material-verification").dispatchEvent(new Event("submit",{bubbles:true,cancelable:true}))');
    await until(() => evaluate('Boolean(document.querySelector(".material-verification [role=status]"))'));
    await evaluate('document.querySelector(".mission-material header button").click()');
    await evaluate('document.querySelector(".hero-actions .cta").click()');
    const studyFrame = await until(() => main.webContents.mainFrame.frames.find(frame => frame.url.endsWith('/study/index.html')));
    await until(() => studyFrame.executeJavaScript('typeof spinCasino === "function"'));
    await studyFrame.executeJavaScript('setFreeMinutes(100); betRange.value="21"; refreshCasinoUI();');
    assert.equal(await studyFrame.executeJavaScript('roulette.style.getPropertyValue("--win-angle")'), '108deg');
    for (const [random, expected] of [[0.1, true], [0.8, false]]) {
      const result = await studyFrame.executeJavaScript(`(async()=>{const original=Math.random;Math.random=()=>${random};try{await spinCasino();return {won:casinoResult.classList.contains("win"),angle:(360-rouletteRotation%360)%360};}finally{Math.random=original;}})()`);
      assert.equal(result.won, expected);
      assert.equal(result.angle < 108, expected);
    }
    await studyFrame.executeJavaScript('currentIndex=totalSlides-1; state[currentIndex].timeSatisfied=true; updateHUD();');
    await until(() => evaluate('Boolean(document.querySelector(".study-complete:not(:disabled)"))'));
    await evaluate('document.querySelector(".study-complete").click()');
    await until(() => evaluate('document.querySelector(".study-complete").textContent.includes("CONCLUÍDA")'));
    await evaluate('document.querySelector(".study-mode header button").click()');
    await evaluate('window.dispatchEvent(new Event("freddy:shop"))');
    await until(() => evaluate('Boolean(document.querySelector(".os-shop-dialog"))'));
    assert.equal(await evaluate('document.querySelector(".os-shop-dialog").textContent.includes("Corredor")'), false);
    assert.equal(await evaluate('document.querySelector(".os-shop-dialog").textContent.includes("Comprar · 50 Study Coins")'), true);
    await evaluate('document.querySelectorAll(".os-skin-grid > button")[1].click()');
    await until(() => evaluate('document.querySelectorAll(".os-skin-grid > button")[1].textContent.includes("EM USO")'));
    assert.equal(await evaluate('window.baiStudyMain.getAcademy().then(state => state.owned.includes("freddy_asa"))'), true);
    await until(() => evaluate('Boolean(document.querySelector(".os-shop-dialog canvas")?.width > 300)'));
    const bikeFrame = await evaluate('(() => { const v=document.querySelector(".os-shop-dialog .matte-video video"); const c=document.createElement("canvas"); c.width=v.videoWidth; c.height=v.videoHeight; c.getContext("2d").drawImage(v,0,0); return c.toDataURL(); })()');
    writeFileSync(join(app.getPath('userData'), 'bike-raw.png'), Buffer.from(bikeFrame.split(',')[1], 'base64'));
    const bikeMatte = await evaluate('document.querySelector(".os-shop-dialog canvas").toDataURL()');
    writeFileSync(join(app.getPath('userData'), 'bike-matte.png'), Buffer.from(bikeMatte.split(',')[1], 'base64'));
    await evaluate('document.querySelector(".os-shop-close").click()');
    for (const mission of missions) {
      const requirement = MATERIAL_PROOFS[mission.id];
      const proof = mission.id === 'jupiter-pilhas' ? { slidesCompleted: true } : requirement ? validProof(requirement) : undefined;
      await evaluate('window.baiStudyMain.updateAcademy(' + JSON.stringify({ type: 'mission.complete', id: mission.id, proof }) + ')');
    }
    await evaluate('window.dispatchEvent(new Event("freddy:shop"))');
    await until(() => evaluate('Boolean(document.querySelector(".os-farewell-unlock button") && !document.querySelector(".os-farewell-unlock button").disabled)'));
    await evaluate('document.querySelector(".os-farewell-unlock button").click()');
    await until(() => evaluate('Boolean(document.querySelector(".os-farewell canvas")?.width > 300)'));
    const media = await evaluate('({ width: document.querySelector(".os-farewell video").videoWidth, height: document.querySelector(".os-farewell video").videoHeight, duration: document.querySelector(".os-farewell video").duration })');
    await pause(500);
    const farewellFrame = await evaluate('document.querySelector(".os-farewell canvas").toDataURL()');
    writeFileSync(join(app.getPath('userData'), 'farewell-matte.png'), Buffer.from(farewellFrame.split(',')[1], 'base64'));
    writeFileSync(join(app.getPath('userData'), 'farewell.png'), (await main.webContents.capturePage()).toPNG());
    await until(() => evaluate('window.baiStudyMain.getSession().then(s => s.phase === "retired")'), Math.ceil(media.duration * 1000) + 10000);
    assert.equal(await evaluate('Boolean(document.querySelector(".desktop-freddy"))'), false);
    assert.equal(await evaluate('Array.from(document.querySelectorAll("button")).some(b => b.getAttribute("aria-label") === "Abrir Foco Total")'), false);
    const finalReels = await evaluate('window.baiStudyInstagram.getReels()');
    assert.ok(finalReels.every(r => !/^reels0[359]\./i.test(r.fileName)));
    assert.ok(finalReels.length > 2);
    assert.equal(await evaluate('window.baiStudyMain.startBuddy().then(() => false, () => true)'), true);
    await evaluate('Array.from(document.querySelectorAll("button")).find(b => b.getAttribute("aria-label") === "Abrir Instagram").click()');
    await pause(100);
    await evaluate('document.querySelector("button[aria-label=Reels]").click()');
    await until(() => evaluate('document.querySelectorAll(".reel").length > 2'));
    assert.equal(await evaluate('document.querySelectorAll(".reel--study").length'), 0);
    console.log(JSON.stringify({ result: 'PASS', missions: missions.length, finalReels: finalReels.map(r => r.fileName), media, artifacts: app.getPath('userData') }));
    app.quit();
  } catch (error) { console.error(error); app.exit(1); }
});
